{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.565Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.573Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.575Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.577Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.578Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:34:37.579Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:34:37.584Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:34:37.864Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO customers (name) VALUES ($1) RETURNING id","timestamp":"2025-04-03T16:34:38.514Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-03T16:34:38.527Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:34:38.532Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"DELETE FROM vehicles WHERE customer_id = $1","timestamp":"2025-04-03T16:34:38.541Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.573Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.589Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.592Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.594Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.596Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:36:20.601Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:36:20.607Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO customers (name) VALUES ($1) RETURNING id","timestamp":"2025-04-03T16:36:20.937Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-03T16:36:20.955Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:36:20.960Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"DELETE FROM vehicles WHERE customer_id = $1","timestamp":"2025-04-03T16:36:20.967Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.403Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.414Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.415Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.416Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.417Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:37:55.421Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:37:55.425Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-03T16:37:55.599Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:37:55.615Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO customers (name) VALUES ($1) RETURNING id","timestamp":"2025-04-03T16:37:55.617Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"DELETE FROM vehicles WHERE customer_id = $1","timestamp":"2025-04-03T16:37:55.629Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.870Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.881Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.882Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.884Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.888Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:46:12.890Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:46:12.895Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:46:13.374Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-03T16:46:13.790Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO customers (name) VALUES ($1) RETURNING id","timestamp":"2025-04-03T16:46:13.795Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:46:13.807Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"DELETE FROM vehicles WHERE customer_id = $1","timestamp":"2025-04-03T16:46:13.815Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.394Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.411Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.413Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.415Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.418Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:47:52.420Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:47:52.432Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:47:52.510Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.871Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.882Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.883Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.885Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.886Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:49:52.887Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:49:52.894Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:49:52.943Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.059Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.070Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.071Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.072Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.074Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:51:59.074Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:51:59.083Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:51:59.101Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:51:59.799Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-03T16:51:59.808Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO customers (name) VALUES ($1) RETURNING id","timestamp":"2025-04-03T16:51:59.811Z"}
{"error":{"code":"28P01","file":"auth.c","length":104,"line":"335","name":"error","routine":"auth_failed","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"DELETE FROM vehicles WHERE customer_id = $1","timestamp":"2025-04-03T16:51:59.822Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.310Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.321Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.322Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.323Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.324Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:28.325Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:52:28.329Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:52:28.412Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.686Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.695Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.697Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.698Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.699Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T16:52:42.699Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T16:52:42.703Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T16:52:42.743Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.968Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.979Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.980Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.981Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.982Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-03T17:09:56.983Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-03T17:09:56.988Z"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"335","message":"Error connecting to database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","service":"vehicle-tracking","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:368:69)\n    at Parser.handlePacket (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:187:21)\n    at Parser.parse (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/parser.ts:102:30)\n    at Socket.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-03T17:09:57.080Z"}
{"address":"172.20.0.2","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Error connecting to database: connect ECONNREFUSED 172.20.0.2:5432","port":5432,"service":"vehicle-tracking","stack":"Error: connect ECONNREFUSED 172.20.0.2:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)","syscall":"connect","timestamp":"2025-04-04T07:45:13.774Z"}
{"error":{"address":"172.20.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-04T07:45:13.777Z"}
{"error":{"address":"172.20.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-04T07:45:15.782Z"}
{"error":{"code":"42703","file":"parse_target.c","length":137,"line":"1075","name":"error","position":"72","routine":"checkInsertTargets","severity":"ERROR"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *","timestamp":"2025-04-04T07:58:18.262Z"}
{"details":{"code":"42703","message":"column \"heading\" of relation \"vehicle_positions\" does not exist","query":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *"},"errorCode":1400,"level":"error","message":"Error processing position: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.create (/app/packages/backend/dist/repositories/positionRepository.js:19:24)\n    at async processNewPosition (/app/packages/backend/dist/services/positionService.js:16:26)\n    at async createPosition (/app/packages/backend/dist/controllers/positionController.js:97:41)","statusCode":500,"timestamp":"2025-04-04T07:58:18.262Z"}
{"details":{"code":"42703","message":"column \"heading\" of relation \"vehicle_positions\" does not exist","query":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *"},"errorCode":1400,"level":"error","message":"Error recording position: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.create (/app/packages/backend/dist/repositories/positionRepository.js:19:24)\n    at async processNewPosition (/app/packages/backend/dist/services/positionService.js:16:26)\n    at async createPosition (/app/packages/backend/dist/controllers/positionController.js:97:41)","statusCode":500,"timestamp":"2025-04-04T07:58:18.263Z"}
{"error":{"code":"42703","file":"parse_target.c","length":137,"line":"1075","name":"error","position":"72","routine":"checkInsertTargets","severity":"ERROR"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *","timestamp":"2025-04-04T07:58:22.026Z"}
{"details":{"code":"42703","message":"column \"heading\" of relation \"vehicle_positions\" does not exist","query":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *"},"errorCode":1400,"level":"error","message":"Error processing position: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.create (/app/packages/backend/dist/repositories/positionRepository.js:19:24)\n    at async processNewPosition (/app/packages/backend/dist/services/positionService.js:16:26)\n    at async createPosition (/app/packages/backend/dist/controllers/positionController.js:97:41)","statusCode":500,"timestamp":"2025-04-04T07:58:22.026Z"}
{"details":{"code":"42703","message":"column \"heading\" of relation \"vehicle_positions\" does not exist","query":"INSERT INTO vehicle_positions (vehicle_id, latitude, longitude, speed, heading, altitude, accuracy) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *"},"errorCode":1400,"level":"error","message":"Error recording position: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.create (/app/packages/backend/dist/repositories/positionRepository.js:19:24)\n    at async processNewPosition (/app/packages/backend/dist/services/positionService.js:16:26)\n    at async createPosition (/app/packages/backend/dist/controllers/positionController.js:97:41)","statusCode":500,"timestamp":"2025-04-04T07:58:22.026Z"}
{"error":{"code":"42703","file":"parse_relation.c","length":104,"line":"3647","name":"error","position":"38","routine":"errorMissingColumn","severity":"ERROR"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"\n      SELECT vp.*, v.license_plate, v.make as vehicle_make, v.model as vehicle_model\n      FROM vehicle_positions vp\n      JOIN vehicles v ON vp.vehicle_id = v.id\n      WHERE v.customer_id = $1\n      AND vp.timestamp = (\n          SELECT MAX(timestamp) \n          FROM vehicle_positions \n          WHERE vehicle_id = vp.vehicle_id\n      )\n      ORDER BY vp.timestamp DESC\n    ","timestamp":"2025-04-04T08:16:47.420Z"}
{"details":{"code":"42703","message":"column v.make does not exist","query":"\n      SELECT vp.*, v.license_plate, v.make as vehicle_make, v.model as vehicle_model\n      FROM vehicle_positions vp\n      JOIN vehicles v ON vp.vehicle_id = v.id\n      WHERE v.customer_id = $1\n     ..."},"errorCode":1400,"level":"error","message":"Error fetching positions: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.getCurrentPositionsByCustomerId (/app/packages/backend/dist/repositories/positionRepository.js:37:24)\n    at async getAllPositions (/app/packages/backend/dist/controllers/positionController.js:17:27)","statusCode":500,"timestamp":"2025-04-04T08:16:47.421Z"}
{"error":{"code":"42703","file":"parse_relation.c","length":104,"line":"3647","name":"error","position":"38","routine":"errorMissingColumn","severity":"ERROR"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"\n      SELECT vp.*, v.license_plate, v.make as vehicle_make, v.model as vehicle_model\n      FROM vehicle_positions vp\n      JOIN vehicles v ON vp.vehicle_id = v.id\n      WHERE v.customer_id = $1\n      AND vp.timestamp = (\n          SELECT MAX(timestamp) \n          FROM vehicle_positions \n          WHERE vehicle_id = vp.vehicle_id\n      )\n      ORDER BY vp.timestamp DESC\n    ","timestamp":"2025-04-04T08:16:51.894Z"}
{"details":{"code":"42703","message":"column v.make does not exist","query":"\n      SELECT vp.*, v.license_plate, v.make as vehicle_make, v.model as vehicle_model\n      FROM vehicle_positions vp\n      JOIN vehicles v ON vp.vehicle_id = v.id\n      WHERE v.customer_id = $1\n     ..."},"errorCode":1400,"level":"error","message":"Error fetching positions: Database query failed","name":"ServerError","service":"vehicle-tracking","stack":"ServerError: Database query failed\n    at query (/app/packages/backend/dist/db/index.js:53:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresPositionRepository.getCurrentPositionsByCustomerId (/app/packages/backend/dist/repositories/positionRepository.js:37:24)\n    at async getAllPositions (/app/packages/backend/dist/controllers/positionController.js:17:27)","statusCode":500,"timestamp":"2025-04-04T08:16:51.894Z"}
{"code":"57P03","file":"postmaster.c","length":104,"level":"error","line":"2337","message":"Error connecting to database: the database system is starting up","name":"error","routine":"ProcessStartupPacket","service":"vehicle-tracking","severity":"FATAL","stack":"error: the database system is starting up\n    at Parser.parseErrorMessage (/app/packages/backend/node_modules/pg-protocol/dist/parser.js:283:98)\n    at Parser.handlePacket (/app/packages/backend/node_modules/pg-protocol/dist/parser.js:122:29)\n    at Parser.parse (/app/packages/backend/node_modules/pg-protocol/dist/parser.js:35:38)\n    at Socket.<anonymous> (/app/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)","timestamp":"2025-04-04T08:56:49.651Z"}
{"error":{"code":"57P03","file":"postmaster.c","length":104,"line":"2337","name":"error","routine":"ProcessStartupPacket","severity":"FATAL"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-04T08:56:49.654Z"}
{"details":{"email":"pouladzade@gmail.com"},"errorCode":1101,"level":"error","message":"Error creating customer: Email is already in use","name":"ConflictError","service":"vehicle-tracking","stack":"ConflictError: Email is already in use\n    at createCustomer (/app/packages/backend/dist/controllers/customerController.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":409,"timestamp":"2025-04-04T08:59:39.519Z"}
{"address":"172.20.0.2","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Error connecting to database: connect ECONNREFUSED 172.20.0.2:5432","port":5432,"service":"vehicle-tracking","stack":"Error: connect ECONNREFUSED 172.20.0.2:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)","syscall":"connect","timestamp":"2025-04-04T09:41:33.212Z"}
{"error":{"address":"172.20.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-04T09:41:33.214Z"}
{"details":{"customerId":3},"errorCode":1001,"level":"error","message":"Authentication error: Invalid customer ID","name":"AuthenticationError","service":"vehicle-tracking","stack":"AuthenticationError: Invalid customer ID\n    at authenticate (/app/packages/backend/dist/controllers/authController.js:29:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":401,"timestamp":"2025-04-04T16:36:10.342Z"}
{"details":{"customerId":3},"errorCode":1001,"level":"error","message":"Authentication error: Invalid customer ID","name":"AuthenticationError","service":"vehicle-tracking","stack":"AuthenticationError: Invalid customer ID\n    at authenticate (/app/packages/backend/dist/controllers/authController.js:29:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":401,"timestamp":"2025-04-04T16:36:11.437Z"}
{"error":{"code":"23505","constraint":"vehicles_license_plate_key","detail":"Key (license_plate)=(ABC123) already exists.","file":"nbtinsert.c","length":231,"line":"663","name":"error","routine":"_bt_check_unique","schema":"public","severity":"ERROR","table":"vehicles"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"INSERT INTO vehicles (license_plate, customer_id) VALUES ($1, $2) RETURNING *","timestamp":"2025-04-04T16:36:32.198Z"}
{"code":"23505","constraint":"vehicles_license_plate_key","detail":"Key (license_plate)=(ABC123) already exists.","file":"nbtinsert.c","length":231,"level":"error","line":"663","message":"Database error during create vehicle: duplicate key value violates unique constraint \"vehicles_license_plate_key\"","name":"error","routine":"_bt_check_unique","schema":"public","service":"vehicle-tracking","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"vehicles_license_plate_key\"\n    at /app/packages/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async query (/app/packages/backend/dist/db/index.js:41:21)\n    at async PostgresVehicleRepository.create (/app/packages/backend/dist/repositories/vehicleRepository.js:24:24)\n    at async addVehicle (/app/packages/backend/dist/controllers/vehicleController.js:77:25)","table":"vehicles","timestamp":"2025-04-04T16:36:32.199Z"}
{"details":{"constraint":"vehicles_license_plate_key","field":"license_plate","value":"ABC123"},"errorCode":1101,"level":"error","message":"Error creating vehicle: A vehicle with this license_plate already exists","name":"ConflictError","service":"vehicle-tracking","stack":"ConflictError: A vehicle with this license_plate already exists\n    at handleDatabaseError (/app/packages/backend/dist/utils/dbErrors.js:53:20)\n    at query (/app/packages/backend/dist/db/index.js:50:54)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresVehicleRepository.create (/app/packages/backend/dist/repositories/vehicleRepository.js:24:24)\n    at async addVehicle (/app/packages/backend/dist/controllers/vehicleController.js:77:25)","statusCode":409,"timestamp":"2025-04-04T16:36:32.199Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.804Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.814Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.816Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.817Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.818Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:04:21.819Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:04:21.824Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.846Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.861Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.862Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.864Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.865Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:05:46.866Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:05:46.873Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.042Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.052Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.054Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.055Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.056Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:07:24.057Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:07:24.062Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.049Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.058Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.059Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.060Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.061Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:09:32.062Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:09:32.066Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.708Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.718Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.720Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.721Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.722Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:10:38.723Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:10:38.728Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.952Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.963Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.964Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.965Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.966Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T17:11:50.967Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T17:11:50.974Z"}
{"address":"172.18.0.2","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Error connecting to database: connect ECONNREFUSED 172.18.0.2:5432","port":5432,"service":"vehicle-tracking","stack":"Error: connect ECONNREFUSED 172.18.0.2:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)","syscall":"connect","timestamp":"2025-04-04T18:18:12.349Z"}
{"error":{"address":"172.18.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"level":"error","message":"Error executing query","service":"vehicle-tracking","text":"SELECT NOW()","timestamp":"2025-04-04T18:18:12.352Z"}
{"code":"23505","constraint":"customers_email_key","detail":"Key (email)=(test@example.com) already exists","file":"","level":"error","line":"","message":"Database error during create customer: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.535Z","where":""}
{"code":"23503","constraint":"vehicles_customer_id_fkey","detail":"Key (customer_id)=(999) is not present in table \"customers\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.546Z","where":""}
{"code":"23502","column":"license_plate","constraint":"","detail":"Null value in column \"license_plate\"","file":"","level":"error","line":"","message":"Database error during create vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.548Z","where":""}
{"code":"08006","constraint":"","detail":"connection error","file":"","level":"error","line":"","message":"Database error during query position: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.549Z","where":""}
{"code":"42703","column":"unknown_column","constraint":"","detail":"Column \"unknown_column\" does not exist","file":"","level":"error","line":"","message":"Database error during query vehicle: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.550Z","where":""}
{"code":"99999","constraint":"","detail":"","file":"","level":"error","line":"","message":"Database error during update driver: Database error","name":"error","routine":"","service":"vehicle-tracking","severity":"ERROR","timestamp":"2025-04-04T18:25:25.554Z","where":""}
{"level":"error","message":"Database error during query trip: Random error","service":"vehicle-tracking","stack":"Error: Random error\n    at Object.<anonymous> (/home/mcmurphy/projects/vehicle-tracking/packages/backend/src/tests/dbErrors.test.ts:130:27)\n    at Promise.then.completed (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:121:9)\n    at run (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/home/mcmurphy/projects/vehicle-tracking/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-04-04T18:25:25.558Z"}
